run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - whitespace

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  goimports:
    local-prefixes: github.com/mattwalters/dipstick
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
